@startuml
Class Resume {
- String uuid
- String fullName
- mapContacts
- mapSections
+getContact()
+getSection()
+getUuid()
+getFullName()
+addSection(SectionType type, SectionValue value)
+addContact(ContactType type, String value)
}

Class ListSection{
-listItems
+equals(Object o)
+hashCode()
+toString()
}

Interface Section{
}

Class TextSection{
-name
+equals(Object o)
+hashCode()
+toString()
}

Class Organization{
-site
-dateStart
-dateEnd
-position
-text
+equals(Object o)
+hashCode()
+toString()
}

Class ContactType {
-title
+String getTitle()
}

Class SectionType {
-title
+String getTitle()
}

Resume *-- SectionType
Resume *-- ContactType
Resume *-- ListSection
Resume *-- TextSection
ListSection *-- Organization
Section <|-- ListSection
Section <|-- TextSection
@enduml